### ISSUE TITLE
Huggingface webcam option locally.

### ISSUE THREAD

**Issue by davebrouwer1** [radames/Real-Time-Latent-Consistency-Model#10]
Hello, I've noticed in the huggingface demo, it asks for my webcam permission, and I have an option to select my webcam in the dropdown, however, I do not seem to have this option with the cloned repo, is there a way to add this feature locally?

**Comment by kimba23** [comment]
I have the same question

**Comment by fofr** [comment]
This answer helped me:
https://stackoverflow.com/a/57376955

**Comment by radames** [comment]
hi all, yes that happened to me as well, specially testing on Safari IOS, the way I solved it was to serve the server using a self-signed SSL

```
openssl req -newkey rsa:4096 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
uvicorn "app-img2img:app" --host 0.0.0.0 --port 7860 --reload --log-level info --ssl-certfile=certificate.pem --ssl-keyfile=key.pem
```

**Comment by Limbicnation** [comment]
I'm encountering an issue when attempting to run the application locally on Firefox; the webcam doesn't appear in the selection options, indicating it's not recognized or initialized by the application.

![image](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/6284675/b0a91ac2-24d5-4fbf-8281-65484311fd43)


Running this command:
`uvicorn "app-img2img:app" --host 0.0.0.0 --port 7860 --reload`

![Screenshot from 2023-11-11 13-05-31](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/6284675/fc3be0ef-b31b-4643-93b1-8bd8db8bb2fb)

**Comment by radames** [comment]
hi @Limbicnation , I just tested it locally on Firefox, and you might need to issue a self signed SSL to serve the app with HTTPs, 

```
openssl req -newkey rsa:4096 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
uvicorn "app-img2img:app" --host 0.0.0.0 --port 7860 --reload --log-level info --ssl-certfile=certificate.pem --ssl-keyfile=key.pem
```
then go to `https://localhost:7860`
![image](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/102277/cc04b3af-20b6-47e2-8506-7dc3ffe20dc3)

**Comment by radames** [comment]
another solution here 

https://github.com/radames/Real-Time-Latent-Consistency-Model/issues/17#issuecomment-1811957196
