### ISSUE TITLE
It's possible to add computer screen capture instead of webcam ?

### ISSUE THREAD

**Issue by alexfredo** [radames/Real-Time-Latent-Consistency-Model#11]
Hi I just want to know if It's possible to add computer screen capture instead of webcam ? thanks

**Comment by radames** [comment]
hi @alexfredo the webcam selection is included on the current main branch, please update your local repo , `git pull`!

**Comment by radames** [comment]
sorry @alexfredo , you could try this https://obsproject.com/kb/virtual-camera-guide
