### ISSUE TITLE
Encountering Webcam Detection Issue on Ubuntu 22.04

### ISSUE THREAD

**Issue by Limbicnation** [radames/Real-Time-Latent-Consistency-Model#12]
Hello,
I've completed the installation process on Ubuntu 22.04. However, when I attempt to run the application, no webcam appears in the selectable device list, indicating that the webcam is not initializing or being recognized.

![image](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/6284675/a54db339-6c50-45dd-ac75-1da5bc902644)

**Comment by radames** [comment]
hi @Limbicnation , I've responded here, please let me know if the SSL would work for you. thanks

https://github.com/radames/Real-Time-Latent-Consistency-Model/issues/10#issuecomment-1806926430

**Comment by Limbicnation** [comment]
Thanks for the explanation, @radames . This worked perfectly!
