### ISSUE TITLE
How to add models?

### ISSUE THREAD

**Issue by ArturFormella** [radames/Real-Time-Latent-Consistency-Model#13]
What is the best method of adding other models to the demo. 
What models will be appropriate?

**Comment by razvanab** [comment]
Using your already-downloaded models will indeed be a nice addition.

**Comment by radames** [comment]
I'm working on a new code base and it will be easier to create your pipelines with different models

**Comment by razvanab** [comment]
Great, thank you!

**Comment by radames** [comment]
Hi @ArturFormella  and @razvanab I have a new codebase now! it's very easy to build new pipelines, please follow the example here
https://github.com/radames/Real-Time-Latent-Consistency-Model/tree/main/pipelines
For now there is only text and image mode. the UI is defined by a pydantic model 
https://github.com/radames/Real-Time-Latent-Consistency-Model/blob/cf3ff1a1d5270b32ea74f8694df3ad077490b096/pipelines/controlnet.py#L34-L129

After you have you pipeline you can run `python run.py --reload --pipeline custompiline` matching the filename. I need to add more instructions, please feel free to ask question here.
