### ISSUE TITLE
No Webcam 

### ISSUE THREAD

**Issue by ameen-roayan** [radames/Real-Time-Latent-Consistency-Model#17]
Hello Everyone, 
for some reason i cant find the option to select a webcam on brave.

![image](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/92278134/3fa1ea1e-04a7-4425-867b-ae2c7587ab87)

Any idea on why its not figuring it out ?

**Comment by radames** [comment]
hi @ameen-roayan , it's a recurrent issue due to browser security issues, you need to serve with a self signed SSL 

https://github.com/radames/Real-Time-Latent-Consistency-Model/issues/10#issuecomment-1806926430

**Comment by ameen-roayan** [comment]
Oh i did those steps but i am still getting stuck on the next step
![image](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/92278134/2049cd3a-c5ec-4037-88b5-affd945798bf)

**Comment by ameen-roayan** [comment]
![image](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/92278134/43053bd5-4cac-42ad-a879-981d5f04bdef)
Actually there are quite a few options missing, its as if there are 2 different index.HTML being loaded

**Comment by radames** [comment]
hi from your first screenshot, it look like something went wrong with the SSL 
![image](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/102277/09f99c00-dcae-42f3-9cdb-c4507a049d98)

The camera options can only be enumerated when the user gives access to the media via browser, that's why you don't see any option there

**Comment by ameen-roayan** [comment]
I have tried the proposed method of getting a signed SSL certificate, nothing wanted to go through, tried several browsers as well but it just wont ever be considered valid for some reason

**Comment by radames** [comment]
hi @ameen-roayan  on chrome you can try this
`http://localhost:7860,http://0.0.0.0:7860`
here
chrome://flags/#unsafely-treat-insecure-origin-as-secure


![image](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/102277/845ca54b-bec7-483a-adbd-c4aa481c3213)

**Comment by ameen-roayan** [comment]
Thank you ! that solved it
