### ISSUE TITLE
macOS Issue: OBS does not show up under Camera selection

### ISSUE THREAD

**Issue by enzyme69** [radames/Real-Time-Latent-Consistency-Model#20]
Not sure if this is recent macOS and OBS issue, but no matter what I could not see the Virtual Camera from OBS. I thought it would be straight forward. Maybe my setting is wrong?

<img width="347" alt="Screenshot 2023-11-15 at 1 26 26 pm" src="https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/3952687/b40916b1-ce36-4ca3-a027-cf9a43d8db09">

Maybe someone can give suggestion?

UPDATE: 
Weird thing however,  seems to work on Chrome, but "Camera Selection" is not really right. I can' see option from my iPhone or from OBS. It simply show up.

**Comment by enzyme69** [comment]
In some random occasion, iPhone back camera or top down camera shows up. My guess like it is only picking the first available camera. When I tested on Safari, earlier, it picks iPhone. When I disconnect my iPhone, it picks the OBS sharing Virtual Camera.

Anyhow, the camera list is not showing properly, might need some code Python fix.

**Comment by Blizaine** [comment]
I had a similar issue and had to upgrade OBS from 29 to 30RC for it to show as a cam in Chrome. Although it looks like 30 was released on Nov 11th so you might already have it.

**Comment by radames** [comment]
hi all, one note, I just release a newer version where you can share a screen directed via the app, for now is a centered frame of 768x768. This might save folks one step 

https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/102277/8e76a580-ded7-4e62-99c6-0aa41f959717

**Comment by enzyme69** [comment]
With this latest issue, I don't get the webcam request like before. 

This used to work before I delete the folder start fresh with latest setup.

```
openssl req -newkey rsa:4096 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
uvicorn "app-txt2imglora:app" --host 0.0.0.0 --port 7810 --reload --log-level info --ssl-certfile=certificate.pem --ssl-keyfile=key.pem
```

Now it's no longer working :(

What's the equivalent of above, but with below new workflow? You seem to make use of frontend. 

```
python -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt
cd frontend && npm install && npm run build && cd ..
python run.py --reload --pipeline controlnet
```

Also how to change specify address?

**Comment by radames** [comment]
yes the same patter as before, the changes mostly are due to unicorn limitation to get arguments, so I have to wrap it inside a `run.py`

```
openssl req -newkey rsa:4096 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
python run.py --reload --ssl-certfile=certificate.pem --ssl-keyfile=key.pem
```

**Comment by enzyme69** [comment]
Ok got it working! Thanks this is superb!

```
source venv/bin/activate
openssl req -newkey rsa:4096 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
python run.py --reload --pipeline controlnet --ssl-certfile=certificate.pem --ssl-keyfile=key.pem --host 0.0.0.0 --port 7826
```

One more thing: 
The final issue is with the placement of the window and how the output is not exactly matching the scale:
<img width="1031" alt="Screenshot 2023-11-22 at 12 39 23 pm" src="https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/3952687/49fb3e81-68d7-48e8-b9c9-1fdacfa71a70">

So this is from Blender, you can see the viewport and the final fusion seems slightly larger. As you can see in my video, I am also having issue to frame the window "square"

https://www.youtube.com/watch?v=jB9pxlNIQGs

**Comment by radames** [comment]
hi @enzyme69 , nice!
Yes the window placement is still very simple, a centered 768x768 square. I can improve it, my idea is a simple drag and drop frame on the left window, showing the whole screen shared, then you can move and positioned the square. 
One issue was the browser Canvas API was not handling well the cropping of large screen, :(

**Comment by enzyme69** [comment]
Thanks, will check again for future update!
