### ISSUE TITLE
Webcam not detected via GUI

### ISSUE THREAD

**Issue by ziadzee** [radames/Real-Time-Latent-Consistency-Model#25]
Hello

Not sure if it's just me but my webcam isn't being detected for some reason. Other applications on my machine are able to detect my camera. Everything on GUI works fine. Using an M2.

![image](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/65977822/d7080597-ea12-4739-b553-1b5cdf9bb12b)

**Comment by dongyun-kim-arch** [comment]
Same here. 
It worked 2 weeks ago, but it is not. It seems the webcam is not activated.

**Comment by radames** [comment]
Hi could you please try it again? there is a new codebase, please update your local repo. Also for chrome you can do this, https://github.com/radames/Real-Time-Latent-Consistency-Model/issues/17#issuecomment-1811957196
