### ISSUE TITLE
No image generated with `txt2imglora`

### ISSUE THREAD

**Issue by umaar** [radames/Real-Time-Latent-Consistency-Model#26]
Running this:

```sh
TIMEOUT=120 SAFETY_CHECKER=True MAX_QUEUE_SIZE=4 python -m uvicorn "app-txt2imglora:app" --host 0.0.0.0 --port 7860 --reload
```

And then clicking Start for the default prompt, I'm not seeing any images produced 

The terminal shows lots of:

```sh
INFO:     127.0.0.1:52917 - "GET /queue_size HTTP/1.1" 200 OK
INFO:     127.0.0.1:52917 - "GET /queue_size HTTP/1.1" 200 OK
INFO:     127.0.0.1:52977 - "GET /queue_size HTTP/1.1" 200 OK
...
```

Gave it around 20 minutes on an M2.

Any ideas?

**Comment by JPW0080** [comment]
On the localhost:7860:
Try this, Start/Advanced Options/Rand

**Comment by radames** [comment]
hi @umaar , first no need to use `TIMEOUT=120 SAFETY_CHECKER=True MAX_QUEUE_SIZE=4 ` if you're running it locally, second I just pushed a newer version and I guess I fixed the Mac issue, I've tested on my M1 and it works now!

**Comment by radames** [comment]
I have a new codebase now, it's very easy to build new pipelines, please follow the example here
https://github.com/radames/Real-Time-Latent-Consistency-Model/tree/main/pipelines
For now there is only text and image mode. the UI is defined by a pydantic model 
https://github.com/radames/Real-Time-Latent-Consistency-Model/blob/cf3ff1a1d5270b32ea74f8694df3ad077490b096/pipelines/controlnet.py#L34-L129

After you have you pipeline you can run `python run.py --reload --pipeline custompiline` matching the filename. I need to add more instructions, please feel free to ask question here.

**Comment by umaar** [comment]
It looks great and is working now, thanks!
