### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by SongWZ3214** [radames/Real-Time-Latent-Consistency-Model#29]
Hello! I deployed the project to local successfully last week. But when I deploy the new version today, the web page cannot be loaded and always reports error 404: Not Found. I want to know how to solve this problem.
![屏幕截图(2174)](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/114729506/90b0c445-54d8-4348-abe0-ac57f0aa12e1)
![屏幕截图(2175)](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/114729506/fdd0ab07-dfec-4516-bfbc-dc35f8f382b1)

**Comment by SongWZ3214** [comment]
Sorry，I had solved the problem!

**Comment by chunzha1** [comment]
> Sorry，I had solved the problem!

hi, I meet the same problem now, can you share how to solve this?

**Comment by SongWZ3214** [comment]
> > Sorry，I had solved the problem!
> 
> hi, I meet the same problem now, can you share how to solve this?

Just update your node to 19 and operate according to the readme document.
