### ISSUE TITLE
where to upload the image

### ISSUE THREAD

**Issue by xcfxr** [radames/Real-Time-Latent-Consistency-Model#33]
![Screenshot from 2023-12-06 10-50-13](https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/73890417/39cc67e3-f0d3-4670-9110-887030be2a24)I have deployed a img2img application, i have clicked everywhere but i could not upload the origin image. The text2img can run successfully.

**Comment by radames** [comment]
hi @xcfxr , there's no option to upload, you can start a video webcam and then share your screen, but there is no option to upload an image. Thanks
