### ISSUE TITLE
Model Speed Up

### ISSUE THREAD

**Issue by acs107102** [radames/Real-Time-Latent-Consistency-Model#35]
Hello, I'm using controlnetSDXLTurbo to do some project.
My machine is RTX 3090.

I'm wondering how can I speed up the result or do you have any recommend model can do that, thanks.

**Comment by radames** [comment]
hi @acs107102 , I'll add some performance improvements soon, meanwhile, could you try [img2imgSD21Turbo.py](https://github.com/radames/Real-Time-Latent-Consistency-Model/blob/main/pipelines/img2imgSD21Turbo.py)  which is the fastest

**Comment by acs107102** [comment]
I'm sorry, I can't find the file you mentioned above.

Btw, I also want to have high-quality video in live stream. Can this model do that?

**Comment by radames** [comment]
hi @acs107102 , please check now, you have the option to use `--onediff` or `--sfast`, it speeds up the inference a bit! please make sure to pul and reinstall `requirements.txt`
