### ISSUE TITLE
TypeError: slice indices must be integers or None or have an index method

### ISSUE THREAD

**Issue by tralala87** [radames/Real-Time-Latent-Consistency-Model#6]
Solution in https://github.com/radames/Real-Time-Latent-Consistency-Model/issues/5 did not resolve issue in my case.

**Comment by radames** [comment]
hi @tralala87 , the issue is the pipeline doesn't have a bounding yet for when you set strength, inference steps and lcm_original_steps , for now just make sure you don't go to very low levels for steps + strength

**Comment by tralala87** [comment]
I've tried different combinations of setting those two parameters, but I always get this error. Although my video is about 1 minute long. Is that too long? Btw, I also get the same error when just runnin ghte img2img

**Comment by radames** [comment]
solved for now, I've remove the option to set the LCM steps, however you will still get an error if the number of steps is too low and the strength
