### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [radames/Real-Time-Latent-Consistency-Model#7]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the Apache-2.0 license to match one of the license headers found in this project and so that others are encouraged to contribute changes back to your project.

**Comment by radames** [comment]
thanks for raising this up! solved

https://github.com/radames/Real-Time-Latent-Consistency-Model/commit/dd1db25dd1449b968a129d7b023661e1a278c66d
